POST http://localhost:8080/v1/formula/save/1
Content-Type: application/json;charset=utf-8

{
    "technology": "4",
    "kind": "1",
    "detail": "[{\"name\":\"5HL\",\"defaultRate\":\"1.39\"},{\"name\":\"4RL\",\"defaultRate\":\"1.19\"}]"
}